mods.extendedcrafting.TableCrafting.addShaped(4, <appliedenergistics2:creative_storage_cell>, [
    [<compacter:cobbler>, <avaritiatweaks:enhancement_crystal>, <denseneutroncollectors:triple_compressed_neutron_collector>, <minecraft:cookie>, <solarflux:solar_panel_infinity>, <minecraft:cookie>, <denseneutroncollectors:triple_compressed_neutron_collector>, <avaritiatweaks:enhancement_crystal>, <compacter:cobbler>],
    [<avaritiatweaks:enhancement_crystal>, <projectex:matter:11>, <ore:ingotInfinity>, <contenttweaker:chaotic_energy_core>, <ore:blockDraconiumAwakened>, <contenttweaker:chaotic_energy_core>, <ore:ingotInfinity>, <projectex:matter:11>, <avaritiatweaks:enhancement_crystal>],
    [<denseneutroncollectors:triple_compressed_neutron_collector>, <ore:ingotInfinity>, <enderstorage:ender_storage>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_void>, <storagedrawers:upgrade_storage:4>, <enderstorage:ender_storage>, <ore:ingotInfinity>, <denseneutroncollectors:triple_compressed_neutron_collector>],
    [<minecraft:cookie>, <contenttweaker:chaotic_energy_core>, <storagedrawers:upgrade_storage:4>, <extendedcrafting:singularity_ultimate>, <storagedrawers:upgrade_creative>, <mekanism:gastank>.withTag({tier: 4}), <storagedrawers:upgrade_storage:4>, <contenttweaker:chaotic_energy_core>, <minecraft:cookie>],
    [<solarflux:solar_panel_infinity>, <ore:blockDraconiumAwakened>, <storagedrawers:upgrade_void>, <storagedrawers:upgrade_creative>, <mysticalagriculture:master_infusion_crystal>, <storagedrawers:upgrade_creative>, <storagedrawers:upgrade_void>, <ore:blockDraconiumAwakened>, <solarflux:solar_panel_infinity>],
    [<minecraft:cookie>, <contenttweaker:chaotic_energy_core>, <storagedrawers:upgrade_storage:4>, <mekanism:gastank>.withTag({tier: 4}), <storagedrawers:upgrade_creative>, <extendedcrafting:singularity_ultimate>, <storagedrawers:upgrade_storage:4>, <contenttweaker:chaotic_energy_core>, <minecraft:cookie>],
    [<denseneutroncollectors:triple_compressed_neutron_collector>, <ore:ingotInfinity>, <enderstorage:ender_storage>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_void>, <storagedrawers:upgrade_storage:4>, <enderstorage:ender_storage>, <ore:ingotInfinity>, <denseneutroncollectors:triple_compressed_neutron_collector>],
    [<avaritiatweaks:enhancement_crystal>, <projectex:matter:11>, <ore:ingotInfinity>, <contenttweaker:chaotic_energy_core>, <ore:blockDraconiumAwakened>, <contenttweaker:chaotic_energy_core>, <ore:ingotInfinity>, <projectex:matter:11>, <avaritiatweaks:enhancement_crystal>],
    [<compacter:cobbler>, <avaritiatweaks:enhancement_crystal>, <denseneutroncollectors:triple_compressed_neutron_collector>, <minecraft:cookie>, <solarflux:solar_panel_infinity>, <minecraft:cookie>, <denseneutroncollectors:triple_compressed_neutron_collector>, <avaritiatweaks:enhancement_crystal>, <compacter:cobbler>]
]);
