// Creative Gas Tank
mods.extendedcrafting.TableCrafting.addShaped(4, <mekanism:gastank>.withTag({tier: 4}), [
    [<mekanism:gasmask>, <aeadditions:storage.gas:6>, <aeadditions:storage.gas:6>, <mekanismgenerators:hohlraum>, <enderio:item_gas_conduit:2>, <mekanismgenerators:hohlraum>, <aeadditions:storage.gas:6>, <aeadditions:storage.gas:6>, <mekanism:gasmask>],
    [<aeadditions:storage.gas:6>, <contenttweaker:chaotic_energy_core>, <draconicevolution:awakened_core>, <advgenerators:fuel_tank>, <extendedcrafting:singularity_ultimate>, <advgenerators:fuel_tank>, <draconicevolution:awakened_core>, <contenttweaker:chaotic_energy_core>, <aeadditions:storage.gas:6>],
    [<aeadditions:storage.gas:6>, <draconicevolution:awakened_core>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "oxygen"}}}), <extendedcrafting:frame>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "hydrogen"}}}), <extendedcrafting:frame>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "brine"}}}), <draconicevolution:awakened_core>, <aeadditions:storage.gas:6>],
    [<mekanismgenerators:hohlraum>, <advgenerators:fuel_tank>, <extendedcrafting:frame>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "sulfurtrioxide"}}}), <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "fusionfuel"}}}), <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "sulfuricacid"}}}), <extendedcrafting:frame>, <advgenerators:fuel_tank>, <mekanismgenerators:hohlraum>],
    [<enderio:item_gas_conduit:2>, <extendedcrafting:singularity_ultimate>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "ethene"}}}), <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "chlorine"}}}), <mekanism:machineblock2:11>.withTag({tier: 4}), <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "water"}}}), <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "sodium"}}}), <extendedcrafting:singularity_ultimate>, <enderio:item_gas_conduit:2>],
    [<mekanismgenerators:hohlraum>, <advgenerators:fuel_tank>, <extendedcrafting:frame>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "lithium"}}}), <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "deuterium"}}}), <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "hydrogenchloride"}}}), <extendedcrafting:frame>, <advgenerators:fuel_tank>, <mekanismgenerators:hohlraum>],
    [<aeadditions:storage.gas:6>, <draconicevolution:awakened_core>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "tritium"}}}), <extendedcrafting:frame>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "sulfurdioxide"}}}), <extendedcrafting:frame>, <mekanism:gastank>.withTag({tier: 3, mekData: {stored: {amount: 512000, gasName: "fusionfuel"}}}), <draconicevolution:awakened_core>, <aeadditions:storage.gas:6>],
    [<aeadditions:storage.gas:6>, <contenttweaker:chaotic_energy_core>, <draconicevolution:awakened_core>, <advgenerators:fuel_tank>, <extendedcrafting:singularity_ultimate>, <advgenerators:fuel_tank>, <draconicevolution:awakened_core>, <contenttweaker:chaotic_energy_core>, <aeadditions:storage.gas:6>],
    [<mekanism:gasmask>, <aeadditions:storage.gas:6>, <aeadditions:storage.gas:6>, <mekanismgenerators:hohlraum>, <enderio:item_gas_conduit:2>, <mekanismgenerators:hohlraum>, <aeadditions:storage.gas:6>, <aeadditions:storage.gas:6>, <mekanism:gasmask>]
]);

// Creative Tank
mods.extendedcrafting.TableCrafting.addShaped(4, <mekanism:machineblock2:11>.withTag({tier: 4}), [
    [<ore:ballInfinity>, <aeadditions:storage.fluid:2>, <aeadditions:storage.fluid:2>, <danknull:dank_null_panel_5>, <actuallyadditions:block_laser_relay_fluids>, <danknull:dank_null_panel_5>, <aeadditions:storage.fluid:2>, <aeadditions:storage.fluid:2>, <ore:ballInfinity>],
    [<aeadditions:storage.fluid:2>, <forge:bucketfilled>.withTag({FluidName: "ender_distillation", Amount: 1000}).noReturn(), <aeadditions:part.base:10>, <appliedenergistics2:part:221>, <actuallyadditions:block_laser_relay_fluids>, <appliedenergistics2:part:221>, <aeadditions:part.base:10>, <forge:bucketfilled>.withTag({FluidName: "ender_distillation", Amount: 1000}).noReturn(), <aeadditions:storage.fluid:2>],
    [<aeadditions:storage.fluid:2>, <aeadditions:part.base:10>, <forge:bucketfilled>.withTag({FluidName: "ender_distillation", Amount: 1000}).noReturn(), <randomthings:spectreilluminator>, <mekanism:machineblock2:11>.withTag({tier: 3, mekData: {fluidTank: {FluidName: "ic2uu_matter", Amount: 112000}}}), <randomthings:spectreilluminator>, <forge:bucketfilled>.withTag({FluidName: "ender_distillation", Amount: 1000}).noReturn(), <aeadditions:part.base:10>, <aeadditions:storage.fluid:2>],
    [<danknull:dank_null_panel_5>, <appliedenergistics2:part:221>, <randomthings:spectreilluminator>, <avaritia:endest_pearl>, <mekanism:machineblock2:11>.withTag({tier: 3, mekData: {fluidTank: {FluidName: "supremium", Amount: 112000}}}), <avaritia:endest_pearl>, <randomthings:spectreilluminator>, <appliedenergistics2:part:221>, <danknull:dank_null_panel_5>],
    [<actuallyadditions:block_laser_relay_fluids>, <actuallyadditions:block_laser_relay_fluids>, <mekanism:machineblock2:11>.withTag({tier: 3, mekData: {fluidTank: {FluidName: "meat", Amount: 112000}}}), <mekanism:machineblock2:11>.withTag({tier: 3, mekData: {fluidTank: {FluidName: "crystal", Amount: 112000}}}), <draconicevolution:creative_rf_source>, <mekanism:machineblock2:11>.withTag({tier: 3, mekData: {fluidTank: {FluidName: "essence", Amount: 112000}}}), <mekanism:machineblock2:11>.withTag({tier: 3, mekData: {fluidTank: {FluidName: "draconium", Amount: 112000}}}), <actuallyadditions:block_laser_relay_fluids>, <actuallyadditions:block_laser_relay_fluids>],
    [<danknull:dank_null_panel_5>, <appliedenergistics2:part:221>, <randomthings:spectreilluminator>, <avaritia:endest_pearl>, <mekanism:machineblock2:11>.withTag({tier: 3, mekData: {fluidTank: {FluidName: "ic2uu_matter", Amount: 112000}}}), <avaritia:endest_pearl>, <randomthings:spectreilluminator>, <appliedenergistics2:part:221>, <danknull:dank_null_panel_5>],
    [<aeadditions:storage.fluid:2>, <aeadditions:part.base:10>, <forge:bucketfilled>.withTag({FluidName: "ender_distillation", Amount: 1000}).noReturn(), <randomthings:spectreilluminator>, <mekanism:machineblock2:11>.withTag({tier: 3, mekData: {fluidTank: {FluidName: "osmiridium", Amount: 112000}}}), <randomthings:spectreilluminator>, <forge:bucketfilled>.withTag({FluidName: "ender_distillation", Amount: 1000}).noReturn(), <aeadditions:part.base:10>, <aeadditions:storage.fluid:2>],
    [<aeadditions:storage.fluid:2>, <forge:bucketfilled>.withTag({FluidName: "ender_distillation", Amount: 1000}).noReturn(), <aeadditions:part.base:10>, <appliedenergistics2:part:221>, <actuallyadditions:block_laser_relay_fluids>, <appliedenergistics2:part:221>, <aeadditions:part.base:10>, <forge:bucketfilled>.withTag({FluidName: "ender_distillation", Amount: 1000}).noReturn(), <aeadditions:storage.fluid:2>],
    [<ore:ballInfinity>, <aeadditions:storage.fluid:2>, <aeadditions:storage.fluid:2>, <danknull:dank_null_panel_5>, <actuallyadditions:block_laser_relay_fluids>, <danknull:dank_null_panel_5>, <aeadditions:storage.fluid:2>, <aeadditions:storage.fluid:2>, <ore:ballInfinity>]
]);
