mods.chisel.Carving.addGroup("peridot");
mods.chisel.Carving.addGroup("ruby");
mods.chisel.Carving.addGroup("sapphire");
mods.chisel.Carving.addVariation("marble",<projectred-exploration:stone:1>);
mods.chisel.Carving.addVariation("peridot", <biomesoplenty:gem_block:2>);
mods.chisel.Carving.addVariation("peridot", <projectred-exploration:stone:7>);
mods.chisel.Carving.addVariation("ruby", <biomesoplenty:gem_block:1>);
mods.chisel.Carving.addVariation("ruby", <projectred-exploration:stone:5>);
mods.chisel.Carving.addVariation("sapphire", <biomesoplenty:gem_block:6>);
mods.chisel.Carving.addVariation("sapphire", <projectred-exploration:stone:6>);