#loader contenttweaker
import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Item;
import mods.contenttweaker.Block;
var AwakenedCorex4=VanillaFactory.createItem("4x_awakened_core");
AwakenedCorex4.register();
var AwakenedCorex8=VanillaFactory.createItem("8x_awakened_core");
AwakenedCorex8.register();
var AwakenedCorex9=VanillaFactory.createItem("9x_awakened_core");
AwakenedCorex9.register();
var AwakenedDraconiumBlockx2=VanillaFactory.createItem("2x_awakened_draconium_block");
AwakenedDraconiumBlockx2.register();
var AwakenedDraconiumBlockx4=VanillaFactory.createItem("4x_awakened_draconium_block");
AwakenedDraconiumBlockx4.register();
var AwakenedDraconiumIngotx4=VanillaFactory.createItem("4x_awakened_draconium_ingot");
AwakenedDraconiumIngotx4.register();
var AwakenedDraconiumIngotx6=VanillaFactory.createItem("6x_awakened_draconium_ingot");
AwakenedDraconiumIngotx6.register();
var AwakenedDraconiumIngotx7=VanillaFactory.createItem("7x_awakened_draconium_ingot");
AwakenedDraconiumIngotx7.register();
var AwakenedDraconiumIngotx8=VanillaFactory.createItem("8x_awakened_draconium_ingot");
AwakenedDraconiumIngotx8.register();
var blueaeter=VanillaFactory.createItem("blue_aeter");
blueaeter.register();
var bluealch=VanillaFactory.createItem("blue_alch");
bluealch.register();
var bluemob=VanillaFactory.createItem("blue_mob");
bluemob.register();
var chaosenergycore=VanillaFactory.createItem("chaotic_energy_core");
chaosenergycore.glowing=true;
chaosenergycore.register();
var Clockx9=VanillaFactory.createItem("9x_clock");
Clockx9.register();
var CrystalMatrixx15=VanillaFactory.createItem("15x_crystal_matrix");
CrystalMatrixx15.register();
var CrystalMatrixx8=VanillaFactory.createItem("8x_crystal_matrix");
CrystalMatrixx8.register();
var darkaeter=VanillaFactory.createItem("dark_aeter");
darkaeter.register();
var darkalch=VanillaFactory.createItem("dark_alch");
darkalch.register();
var DarkMatterx24=VanillaFactory.createItem("24x_dark_matter");
DarkMatterx24.register();
var DarkMatterx26=VanillaFactory.createItem("26x_dark_matter");
DarkMatterx26.register();
var DarkMatterx27=VanillaFactory.createItem("27x_dark_matter");
DarkMatterx27.register();
var DarkMatterx32=VanillaFactory.createItem("32x_dark_matter");
DarkMatterx32.register();
var DarkMatterx64=VanillaFactory.createItem("64x_dark_matter");
DarkMatterx64.register();
var darkmob=VanillaFactory.createItem("dark_mob");
darkmob.register();
var DraconicCorex4=VanillaFactory.createItem("4x_draconic_core");
DraconicCorex4.register();
var DraconicEnergyCorex6=VanillaFactory.createItem("6x_draconic_energy_core");
DraconicEnergyCorex6.register();
var DraconicEnergyCorex8=VanillaFactory.createItem("8x_draconic_energy_core");
DraconicEnergyCorex8.register();
var DraconicEnergyCorex9=VanillaFactory.createItem("9x_draconic_energy_core");
DraconicEnergyCorex9.register();
var enrichedIronBlock=VanillaFactory.createBlock("enriched_iron_block", <blockmaterial:iron>);
enrichedIronBlock.setToolClass("pickaxe");
enrichedIronBlock.setBlockResistance(35.0);
enrichedIronBlock.setToolLevel(3);
enrichedIronBlock.register();
var entityclump=VanillaFactory.createItem("entity_clump");
entityclump.register();
var Featherx32=VanillaFactory.createItem("32x_feather");
Featherx32.register();
var glowred=VanillaFactory.createItem("glowing_redstone_dust");
glowred.register();
var Glowstonex18=VanillaFactory.createItem("18x_glowstone");
Glowstonex18.register();
var Glowstonex2=VanillaFactory.createItem("2x_glowstone");
Glowstonex2.register();
var Glowstonex64=VanillaFactory.createItem("64x_glowstone");
Glowstonex64.register();
var greenaeter=VanillaFactory.createItem("green_aeter");
greenaeter.register();
var greenalch=VanillaFactory.createItem("green_alch");
greenalch.register();
var greenMatterBlock=VanillaFactory.createBlock("gm_block", <blockmaterial:iron>);
greenMatterBlock.setToolClass("pickaxe");
greenMatterBlock.setBlockResistance(18000000.0);
greenMatterBlock.setToolLevel(5);
greenMatterBlock.register();
var greenmob=VanillaFactory.createItem("green_mob");
greenmob.register();
var InfinityCatalystx3=VanillaFactory.createItem("3x_infinity_catalyst");
InfinityCatalystx3.register();
var InfinityIngotx11=VanillaFactory.createItem("11x_infinity_ingot");
InfinityIngotx11.register();
var InfinityIngotx4=VanillaFactory.createItem("4x_infinity_ingot");
InfinityIngotx4.register();
var InfinityIngotx5=VanillaFactory.createItem("5x_infinity_ingot");
InfinityIngotx5.register();
var IronBandx20=VanillaFactory.createItem("20x_iron_band");
IronBandx20.register();
var IronBandx59=VanillaFactory.createItem("59x_iron_band");
IronBandx59.register();
var IronIngotx16=VanillaFactory.createItem("16x_iron_ingot");
IronIngotx16.register();
var IronIngotx34=VanillaFactory.createItem("34x_iron_ingot");
IronIngotx34.register();
var IronIngotx64=VanillaFactory.createItem("64x_iron_ingot");
IronIngotx64.register();
var LapisLazulix43=VanillaFactory.createItem("43x_lapis_lazuli");
LapisLazulix43.register();
var LapisLazulix63=VanillaFactory.createItem("63x_lapis_lazuli");
LapisLazulix63.register();
var NeutroniumBlockx12=VanillaFactory.createItem("12x_neutronium_block");
NeutroniumBlockx12.register();
var NeutroniumBlockx19=VanillaFactory.createItem("19x_neutronium_block");
NeutroniumBlockx19.register();
var NeutroniumBlockx8=VanillaFactory.createItem("8x_neutronium_block");
NeutroniumBlockx8.register();
var NeutroniumIngotx31=VanillaFactory.createItem("31x_neutronium_ingot");
NeutroniumIngotx31.register();
var Obsidianx18=VanillaFactory.createItem("18x_obsidian");
Obsidianx18.register();
var orangeaeter=VanillaFactory.createItem("orange_aeter");
orangeaeter.register();
var orangealch=VanillaFactory.createItem("orange_alch");
orangealch.register();
var orangemob=VanillaFactory.createItem("orange_mob");
orangemob.register();
var rainaeter=VanillaFactory.createItem("rain_aeter");
rainaeter.register();
var rainalch=VanillaFactory.createItem("rain_alch");
rainalch.register();
var rainMatter=VanillaFactory.createItem("rainbow_matter");
rainMatter.register();
var rainMatterBlock=VanillaFactory.createBlock("rainbow_block", <blockmaterial:iron>);
rainMatterBlock.register();
var rainmob=VanillaFactory.createItem("rain_mob");
rainmob.register();
var RedMatterx22=VanillaFactory.createItem("22x_red_matter");
RedMatterx22.register();
var RedMatterx63=VanillaFactory.createItem("63x_red_matter");
RedMatterx63.register();
var RedMatterx64=VanillaFactory.createItem("64x_red_matter");
RedMatterx64.register();
var Sugarx10=VanillaFactory.createItem("10x_sugar");
Sugarx10.register();
var Sugarx11=VanillaFactory.createItem("11x_sugar");
Sugarx11.register();
var Woolx12=VanillaFactory.createItem("12x_wool");
Woolx12.register();
var Woolx32=VanillaFactory.createItem("32x_wool");
Woolx32.register();
var yellowaeter=VanillaFactory.createItem("yellow_aeter");
yellowaeter.register();
var yellowalch=VanillaFactory.createItem("yellow_alch");
yellowalch.register();
var yellowmob=VanillaFactory.createItem("yellow_mob");
yellowmob.register();
var karatCoalOre=VanillaFactory.createItem("karat_seed_coal_ore");
karatCoalOre.register();
var karatIronOre=VanillaFactory.createItem("karat_seed_iron_ore");
karatIronOre.register();
var karatGoldOre=VanillaFactory.createItem("karat_seed_gold_ore");
karatGoldOre.register();
var karatRedstoneOre=VanillaFactory.createItem("karat_seed_redstone_ore");
karatRedstoneOre.register();
var karatLapisOre=VanillaFactory.createItem("karat_seed_lapis_ore");
karatLapisOre.register();
var karatEmeraldOre=VanillaFactory.createItem("karat_seed_emerald_ore");
karatEmeraldOre.register();
var karatDiamondOre=VanillaFactory.createItem("karat_seed_diamond_ore");
karatDiamondOre.register();
var karatQuartzOre=VanillaFactory.createItem("karat_seed_quartz_ore");
karatQuartzOre.register();
var karatCoalBlock=VanillaFactory.createItem("karat_seed_coal_block");
karatCoalBlock.register();
var karatIronBlock=VanillaFactory.createItem("karat_seed_iron_block");
karatIronBlock.register();
var karatGoldBlock=VanillaFactory.createItem("karat_seed_gold_block");
karatGoldBlock.register();
var karatRedstoneBlock=VanillaFactory.createItem("karat_seed_redstone_block");
karatRedstoneBlock.register();
var karatLapisBlock=VanillaFactory.createItem("karat_seed_lapis_block");
karatLapisBlock.register();
var karatEmeraldBlock=VanillaFactory.createItem("karat_seed_emerald_block");
karatEmeraldBlock.register();
var karatDiamondBlock=VanillaFactory.createItem("karat_seed_diamond_block");
karatDiamondBlock.register();
var karatQuartzBlock=VanillaFactory.createItem("karat_seed_quartz_block");
karatQuartzBlock.register();