#Creative Essence
mods.extendedcrafting.TableCrafting.addShaped(4, <mysticalagradditions:stuff:69> * 4, [
	[<simplyjetpacks:metaitemmods:19>, <projectred-core:resource_item:509>, <ore:essenceTier6>, <ore:dyeBlue>, <extrautils2:klein>, <ore:dyeBlue>, <ore:essenceTier6>, <projectred-core:resource_item:509>, <simplyjetpacks:metaitemmods:19>],
	[<projectred-core:resource_item:509>, <simplyjetpacks:metaitemmods:6>, <simplyjetpacks:metaitemmods:21>, <ore:essenceTier6>, <ic2:rotor_carbon>, <ore:essenceTier6>, <simplyjetpacks:metaitemmods:21>, <simplyjetpacks:metaitemmods:6>, <projectred-core:resource_item:509>],
	[<ore:essenceTier6>, <simplyjetpacks:metaitemmods:21>, <ore:dustDraconium>, <extendedcrafting:material:18>, <extendedcrafting:material:18>, <extendedcrafting:material:18>, <ore:dustDraconium>, <simplyjetpacks:metaitemmods:21>, <ore:essenceTier6>],
	[<ore:dyeBlue>, <ore:essenceTier6>, <extendedcrafting:material:18>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <extendedcrafting:material:18>, <ore:essenceTier6>, <ore:dyeBlue>],
	[<extrautils2:klein>, <ic2:rotor_carbon>, <extendedcrafting:material:18>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <extendedcrafting:material:18>, <ic2:rotor_carbon>, <extrautils2:klein>],
	[<ore:dyeBlue>, <ore:essenceTier6>, <extendedcrafting:material:18>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <ore:blockInsaniumEssence>, <extendedcrafting:material:18>, <ore:essenceTier6>, <ore:dyeBlue>],
	[<ore:essenceTier6>, <simplyjetpacks:metaitemmods:21>, <ore:dustDraconium>, <extendedcrafting:material:18>, <extendedcrafting:material:18>, <extendedcrafting:material:18>, <ore:dustDraconium>, <simplyjetpacks:metaitemmods:21>, <ore:essenceTier6>],
	[<projectred-core:resource_item:509>, <simplyjetpacks:metaitemmods:6>, <simplyjetpacks:metaitemmods:21>, <ore:essenceTier6>, <ic2:rotor_carbon>, <ore:essenceTier6>, <simplyjetpacks:metaitemmods:21>, <simplyjetpacks:metaitemmods:6>, <projectred-core:resource_item:509>],
	[<simplyjetpacks:metaitemmods:19>, <projectred-core:resource_item:509>, <ore:essenceTier6>, <ore:dyeBlue>, <extrautils2:klein>, <ore:dyeBlue>, <ore:essenceTier6>, <projectred-core:resource_item:509>, <simplyjetpacks:metaitemmods:19>]
]);

#Creative Storage Upgrade
recipes.addShaped(<storagedrawers:upgrade_creative>, [[<industrialforegoing:black_hole_unit>, <ore:drawerBasic>, <industrialforegoing:black_hole_tank>],[<storagedrawers:upgrade_storage:4>, <industrialforegoing:black_hole_controller_reworked>, <storagedrawers:upgrade_storage:4>], [<storagedrawers:controller>, <rftools:creative_screen>, <storagedrawers:compdrawers>]]);

#Creative Screen
mods.extendedcrafting.TableCrafting.addShaped(4, <rftools:creative_screen>, [
	[<ore:nuggetUltimate>, <mysticalagradditions:stuff:69>, <rftools:screen>, <rftools:screen>, <rftoolsdim:dimension_module>, <rftools:screen>, <rftools:screen>, <mysticalagradditions:stuff:69>, <ore:nuggetUltimate>],
	[<mysticalagradditions:stuff:69>, <minecraft:end_crystal>, <extendedcrafting:singularity:4>, <appliedenergistics2:material:47>, <ore:nuggetUltimate>, <appliedenergistics2:material:47>, <extendedcrafting:singularity:3>, <minecraft:end_crystal>, <mysticalagradditions:stuff:69>],
	[<rftools:screen>, <extendedcrafting:singularity:3>, <rftools:clock_module>, <rftools:dump_module>, <rftools:text_module>, <rftools:inventoryplus_module>, <rftools:redstone_module>, <extendedcrafting:singularity:4>, <rftools:screen>],
	[<rftools:screen>, <appliedenergistics2:material:47>, <rftools:machineinformation_module>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <rftools:energyplus_module>, <appliedenergistics2:material:47>, <rftools:screen>],
	[<rftoolspower:information_screen>, <ore:nuggetUltimate>, <rftoolscontrol:vectorart_module>, <mysticalagradditions:stuff:69>, <rftools:screen>, <mysticalagradditions:stuff:69>, <rftoolscontrol:console_module>, <ore:nuggetUltimate>, <rftools:counterplus_module>],
	[<rftools:screen>, <appliedenergistics2:material:47>, <rftools:storage_control_module>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <mysticalagradditions:stuff:69>, <rftoolscontrol:variable_module>, <appliedenergistics2:material:47>, <rftools:screen>],
	[<rftools:screen>, <extendedcrafting:singularity:4>, <rftools:computer_module>, <rftoolscontrol:interaction_module>, <rftools:button_module>, <rftools:fluidplus_module>, <rftools:elevator_button_module>, <extendedcrafting:singularity:3>, <rftools:screen>],
	[<mysticalagradditions:stuff:69>, <minecraft:end_crystal>, <extendedcrafting:singularity:3>, <appliedenergistics2:material:47>, <ore:nuggetUltimate>, <appliedenergistics2:material:47>, <extendedcrafting:singularity:4>, <minecraft:end_crystal>, <mysticalagradditions:stuff:69>],
	[<ore:nuggetUltimate>, <mysticalagradditions:stuff:69>, <rftools:screen>, <rftools:screen>, <rftools:screen_controller>, <rftools:screen>, <rftools:screen>, <mysticalagradditions:stuff:69>, <ore:nuggetUltimate>]
]);

#Creative Cobble Generator
mods.extendedcrafting.TableCrafting.addShaped(4, <compacter:cobbler>, [
	[<storagedrawers:upgrade_creative>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <enderio:item_capacitor_stellar>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <storagedrawers:upgrade_creative>],
	[<ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>],
	[<ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>],
	[<ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <industrialforegoing:material_stonework_factory>, <ore:xuUpgradeMining>, <industrialforegoing:material_stonework_factory>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>],
	[<enderio:item_capacitor_stellar>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:xuUpgradeMining>, <ore:foodCobblestonecobbler>, <ore:xuUpgradeMining>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <enderio:item_capacitor_stellar>],
	[<ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <industrialforegoing:material_stonework_factory>, <ore:xuUpgradeMining>, <industrialforegoing:material_stonework_factory>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>],
	[<ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>],
	[<ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>],
	[<storagedrawers:upgrade_creative>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <enderio:item_capacitor_stellar>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <ore:compressed6xCobblestone>, <storagedrawers:upgrade_creative>]
]);

#Creative Modifier
mods.extendedcrafting.TableCrafting.addShaped(4, <tconstruct:materials:50>, [
	[<tconstruct:sharpening_kit>.withTag({Material:"platinum_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"enderium_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"lumium_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"awakened_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"wyvern_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"chaotic_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"certusquartz_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"fluix"}), <tconstruct:sharpening_kit>.withTag({Material:"pigiron"})],
	[<tconstruct:sharpening_kit>.withTag({Material:"alumite"}), <tconstruct:sharpening_kit>.withTag({Material:"firewood"}), <tconstruct:sharpening_kit>.withTag({Material:"sponge"}), <tconstruct:sharpening_kit>.withTag({Material:"paper"}), <tconstruct:sharpening_kit>.withTag({Material:"endstone"}), <tconstruct:sharpening_kit>.withTag({Material:"ma.prosperity"}), <tconstruct:sharpening_kit>.withTag({Material:"end_steel"}), <tconstruct:sharpening_kit>.withTag({Material:"stone"}), <tconstruct:sharpening_kit>.withTag({Material:"flint"})],
	[<tconstruct:sharpening_kit>.withTag({Material:"bone"}), <tconstruct:sharpening_kit>.withTag({Material:"palis_actadd_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"electrical_steel"}), <tconstruct:sharpening_kit>.withTag({Material:"osmiridium"}), <tconstruct:sharpening_kit>.withTag({Material:"mithril"}), <tconstruct:sharpening_kit>.withTag({Material:"signalum"}), <tconstruct:sharpening_kit>.withTag({Material:"ma.base_essence"}), <tconstruct:sharpening_kit>.withTag({Material:"prismarine"}), <tconstruct:sharpening_kit>.withTag({Material:"construction_alloy"})],
	[<tconstruct:sharpening_kit>.withTag({Material:"energetic_alloy"}), <tconstruct:sharpening_kit>.withTag({Material:"xu_demonic_metal"}), <tconstruct:sharpening_kit>.withTag({Material:"constantan"}), <ore:boneWithered>, <mekanism:tierinstaller:3>, <tconstruct:materials:19>, <tconstruct:sharpening_kit>.withTag({Material:"invar"}), <tconstruct:sharpening_kit>.withTag({Material:"copper"}), <tconstruct:sharpening_kit>.withTag({Material:"bronze"})],
	[<tconstruct:sharpening_kit>.withTag({Material:"lead"}), <tconstruct:sharpening_kit>.withTag({Material:"silver"}), <tconstruct:sharpening_kit>.withTag({Material:"redstone_alloy"}), <compacter:cobbler>, <extendedcrafting:material:13>, <compacter:cobbler>, <tconstruct:sharpening_kit>.withTag({Material:"conductive_iron"}), <tconstruct:sharpening_kit>.withTag({Material:"electrum"}), <tconstruct:sharpening_kit>.withTag({Material:"steel"})],
	[<tconstruct:sharpening_kit>.withTag({Material:"xu_magical_wood"}), <tconstruct:sharpening_kit>.withTag({Material:"xu_evil_metal"}), <tconstruct:sharpening_kit>.withTag({Material:"tin"}), <tconstruct:materials:14>, <mekanism:tierinstaller:3>, <tconstruct:materials:16>, <tconstruct:sharpening_kit>.withTag({Material:"nickel"}), <tconstruct:sharpening_kit>.withTag({Material:"xu_enchanted_metal"}), <tconstruct:sharpening_kit>.withTag({Material:"knightslime"})],
	[<tconstruct:sharpening_kit>.withTag({Material:"emerald_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"wood"}), <tconstruct:sharpening_kit>.withTag({Material:"blackquartz_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"restonia_actadd_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"enori_actadd_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"signalum_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"emeradic_actadd_plustic"}), <tconstruct:sharpening_kit>.withTag({Material:"netherrack"}), <tconstruct:sharpening_kit>.withTag({Material:"void_actadd_plustic"})],
	[<tconstruct:sharpening_kit>.withTag({Material:"cactus"}), <tconstruct:sharpening_kit>.withTag({Material:"manyullyn"}), <tconstruct:sharpening_kit>.withTag({Material:"ma.soulium"}), <tconstruct:sharpening_kit>.withTag({Material:"ludicrite"}), <tconstruct:sharpening_kit>.withTag({Material:"peridot"}), <tconstruct:sharpening_kit>.withTag({Material:"draconium"}), <tconstruct:sharpening_kit>.withTag({Material:"pulsating_iron"}), <tconstruct:sharpening_kit>.withTag({Material:"rubber"}), <tconstruct:sharpening_kit>.withTag({Material:"diamatine_actadd_plustic"})],
	[<tconstruct:sharpening_kit>.withTag({Material:"electrumflux"}), <tconstruct:sharpening_kit>.withTag({Material:"osgloglas"}), <tconstruct:sharpening_kit>.withTag({Material:"ruby"}), <tconstruct:sharpening_kit>.withTag({Material:"sapphire"}), <tconstruct:sharpening_kit>.withTag({Material:"ma.supremium"}), <tconstruct:sharpening_kit>.withTag({Material:"magmaslime"}), <tconstruct:sharpening_kit>.withTag({Material:"pink_slime"}), <tconstruct:sharpening_kit>.withTag({Material:"blueslime"}), <tconstruct:sharpening_kit>.withTag({Material:"slime"})]
]);

#Creative Energy Cell (AE2)
mods.extendedcrafting.TableCrafting.addShaped(4, <appliedenergistics2:creative_energy_cell>, [
	[<extracells:storage.component:3>, <ore:blockChargedCertusQuartz>, <ore:blockChargedCertusQuartz>, <extendedcrafting:trimmed:5>, <advanced_solar_panels:machines:5>, <extendedcrafting:trimmed:5>, <ore:blockChargedCertusQuartz>, <ore:blockChargedCertusQuartz>, <extracells:storage.component:3>],
	[<ore:blockChargedCertusQuartz>, <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor:1>, <wct:wct>, <wct:wct>, <wct:wct>, <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor:1>, <ore:blockChargedCertusQuartz>],
	[<ore:blockChargedCertusQuartz>, <draconicevolution:draconium_capacitor:1>, <extendedcrafting:singularity_custom:9>, <extendedcrafting:singularity_custom:8>, <enderio:item_capacitor_stellar>, <extendedcrafting:singularity_custom:8>, <extendedcrafting:singularity_custom:9>, <draconicevolution:draconium_capacitor:1>, <ore:blockChargedCertusQuartz>],
	[<extendedcrafting:trimmed:5>, <wct:wct>, <extendedcrafting:singularity_custom:8>, <mekanism:basicblock2:3>.withTag({tier:3}), <mekanism:basicblock2:3>.withTag({tier:3}), <mekanism:basicblock2:3>.withTag({tier:3}), <extendedcrafting:singularity_custom:8>, <wct:wct>, <extendedcrafting:trimmed:5>],
	[<advanced_solar_panels:machines:5>, <wct:wct>, <enderio:item_capacitor_stellar>, <mekanism:basicblock2:3>.withTag({tier:3}), <tconstruct:materials:50>, <mekanism:basicblock2:3>.withTag({tier:3}), <enderio:item_capacitor_stellar>, <wct:wct>, <advanced_solar_panels:machines:5>],
	[<extendedcrafting:trimmed:5>, <wct:wct>, <extendedcrafting:singularity_custom:8>, <mekanism:basicblock2:3>.withTag({tier:3}), <mekanism:basicblock2:3>.withTag({tier:3}), <mekanism:basicblock2:3>.withTag({tier:3}), <extendedcrafting:singularity_custom:8>, <wct:wct>, <extendedcrafting:trimmed:5>],
	[<ore:blockChargedCertusQuartz>, <draconicevolution:draconium_capacitor:1>, <extendedcrafting:singularity_custom:9>, <extendedcrafting:singularity_custom:8>, <enderio:item_capacitor_stellar>, <extendedcrafting:singularity_custom:8>, <extendedcrafting:singularity_custom:9>, <draconicevolution:draconium_capacitor:1>, <ore:blockChargedCertusQuartz>],
	[<ore:blockChargedCertusQuartz>, <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor:1>, <wct:wct>, <wct:wct>, <wct:wct>, <draconicevolution:draconium_capacitor:1>, <draconicevolution:draconium_capacitor:1>, <ore:blockChargedCertusQuartz>],
	[<extracells:storage.component:3>, <ore:blockChargedCertusQuartz>, <ore:blockChargedCertusQuartz>, <extendedcrafting:trimmed:5>, <advanced_solar_panels:machines:5>, <extendedcrafting:trimmed:5>, <ore:blockChargedCertusQuartz>, <ore:blockChargedCertusQuartz>, <extracells:storage.component:3>]
]);

#Creative Turbine Steam Generator
mods.extendedcrafting.TableCrafting.addShaped(4, <bigreactors:turbinecreativesteamgenerator>, [
	[<extendedcrafting:singularity:32>, <ore:blockLudicrite>, <ore:blockLudicrite>, <ore:blockLudicrite>, <ore:blockLudicrite>, <ore:blockLudicrite>, <ore:blockLudicrite>, <ore:blockLudicrite>, <extendedcrafting:singularity:32>],
	[<ore:blockLudicrite>, <extendedcrafting:singularity:32>, <bigreactors:turbinecontroller>, <bigreactors:turbinecontroller>, <simplyjetpacks:metaitemmods:21>, <bigreactors:turbinecontroller>, <bigreactors:turbinecontroller>, <extendedcrafting:singularity:32>, <ore:blockLudicrite>],
	[<ore:blockLudicrite>, <bigreactors:turbinecontroller>, <extendedcrafting:singularity:32>, <bigreactors:turbinefluidport>, <bigreactors:turbinefluidport>, <bigreactors:turbinefluidport>, <extendedcrafting:singularity:32>, <bigreactors:turbinecontroller>, <ore:blockLudicrite>],
	[<ore:blockLudicrite>, <bigreactors:turbinecontroller>, <bigreactors:turbinefluidport>, <extendedcrafting:singularity:32>, <bigreactors:turbinepowertaprf>, <extendedcrafting:singularity:32>, <bigreactors:turbinefluidport>, <bigreactors:turbinecontroller>, <ore:blockLudicrite>],
	[<ore:blockLudicrite>, <simplyjetpacks:metaitemmods:21>, <bigreactors:turbinefluidport>, <bigreactors:turbinepowertaprf>, <tconstruct:materials:50>, <bigreactors:turbinepowertaprf>, <bigreactors:turbinefluidport>, <simplyjetpacks:metaitemmods:21>, <ore:blockLudicrite>],
	[<ore:blockLudicrite>, <bigreactors:turbinecontroller>, <bigreactors:turbinefluidport>, <extendedcrafting:singularity:32>, <bigreactors:turbinepowertaprf>, <extendedcrafting:singularity:32>, <bigreactors:turbinefluidport>, <bigreactors:turbinecontroller>, <ore:blockLudicrite>],
	[<ore:blockLudicrite>, <bigreactors:turbinecontroller>, <extendedcrafting:singularity:32>, <bigreactors:turbinefluidport>, <bigreactors:turbinefluidport>, <bigreactors:turbinefluidport>, <extendedcrafting:singularity:32>, <bigreactors:turbinecontroller>, <ore:blockLudicrite>],
	[<ore:blockLudicrite>, <extendedcrafting:singularity:32>, <bigreactors:turbinecontroller>, <bigreactors:turbinecontroller>, <bigreactors:wrench>, <bigreactors:turbinecontroller>, <bigreactors:turbinecontroller>, <extendedcrafting:singularity:32>, <ore:blockLudicrite>],
	[<extendedcrafting:singularity:32>, <ore:blockLudicrite>, <ore:blockLudicrite>, <ore:blockLudicrite>, <ore:blockLudicrite>, <ore:blockLudicrite>, <ore:blockLudicrite>, <ore:blockLudicrite>, <extendedcrafting:singularity:32>]
]);

#Creative Mill
mods.extendedcrafting.TableCrafting.addShaped(4, <extrautils2:passivegenerator:6>, [
	[<extrautils2:rainbowgenerator>, <extrautils2:rainbowgenerator>, <ore:blockUltimate>, <ore:blockUltimate>, <extendedcrafting:singularity:2>, <ore:blockUltimate>, <ore:blockUltimate>, <extrautils2:rainbowgenerator>, <extrautils2:rainbowgenerator>],
	[<extrautils2:rainbowgenerator>, <extrautils2:passivegenerator:5>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:7>, <extrautils2:passivegenerator:4>, <extrautils2:passivegenerator:7>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:5>, <extrautils2:rainbowgenerator>],
	[<ore:blockUltimate>, <extrautils2:passivegenerator:8>, <appliedenergistics2:creative_energy_cell>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:2>, <bigreactors:turbinecreativesteamgenerator>, <extrautils2:passivegenerator:8>, <ore:blockUltimate>],
	[<ore:blockUltimate>, <extrautils2:passivegenerator:7>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator>, <extrautils2:passivegenerator:1>, <extrautils2:passivegenerator>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:7>, <ore:blockUltimate>],
	[<extendedcrafting:singularity:1>, <extrautils2:passivegenerator:4>, <extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:1>, <compacter:cobbler>, <extrautils2:passivegenerator:1>, <extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:4>, <extendedcrafting:singularity:1>],
	[<ore:blockUltimate>, <extrautils2:passivegenerator:7>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator>, <extrautils2:passivegenerator:1>, <extrautils2:passivegenerator>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:7>, <ore:blockUltimate>],
	[<ore:blockUltimate>, <extrautils2:passivegenerator:8>, <bigreactors:turbinecreativesteamgenerator>, <extrautils2:passivegenerator:2>, <extrautils2:passivegenerator:3>, <extrautils2:passivegenerator:2>, <appliedenergistics2:creative_energy_cell>, <extrautils2:passivegenerator:8>, <ore:blockUltimate>],
	[<extrautils2:rainbowgenerator>, <extrautils2:passivegenerator:5>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:7>, <extrautils2:passivegenerator:4>, <extrautils2:passivegenerator:7>, <extrautils2:passivegenerator:8>, <extrautils2:passivegenerator:5>, <extrautils2:rainbowgenerator>],
	[<extrautils2:rainbowgenerator>, <extrautils2:rainbowgenerator>, <ore:blockUltimate>, <ore:blockUltimate>, <extendedcrafting:singularity:2>, <ore:blockUltimate>, <ore:blockUltimate>, <extrautils2:rainbowgenerator>, <extrautils2:rainbowgenerator>]
]);

#Creative Generator (IC2)
mods.extendedcrafting.TableCrafting.addShaped(4, <ic2:te:86>, [
	[<advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>],
	[<advanced_solar_panels:machines:5>, <ore:ingotUnstable>, <ic2:upgrade>, <ic2:upgrade>, <enderio:block_cap_bank:3>, <ic2:upgrade>, <ic2:upgrade>, <draconicevolution:generator>, <advanced_solar_panels:machines:5>],
	[<advanced_solar_panels:machines:5>, <ic2:upgrade>, <auxiliumequivalence:fuel:10>, <auxiliumequivalence:fuel:10>, <compactmachines3:machine:5>, <auxiliumequivalence:fuel:10>, <auxiliumequivalence:fuel:10>, <ic2:upgrade>, <advanced_solar_panels:machines:5>],
	[<advanced_solar_panels:machines:5>, <ic2:upgrade>, <auxiliumequivalence:fuel:10>, <bigreactors:turbinecreativesteamgenerator>, <extendedcrafting:singularity:35>, <appliedenergistics2:creative_energy_cell>, <auxiliumequivalence:fuel:10>, <ic2:upgrade>, <advanced_solar_panels:machines:5>],
	[<advanced_solar_panels:machines:5>, <enderio:block_cap_bank:3>, <compactmachines3:machine:5>, <extendedcrafting:singularity:35>, <extrautils2:passivegenerator:6>, <extendedcrafting:singularity:35>, <compactmachines3:machine:5>, <enderio:block_cap_bank:3>, <advanced_solar_panels:machines:5>],
	[<advanced_solar_panels:machines:5>, <ic2:upgrade>, <auxiliumequivalence:fuel:10>, <appliedenergistics2:creative_energy_cell>, <extendedcrafting:singularity:35>, <bigreactors:turbinecreativesteamgenerator>, <auxiliumequivalence:fuel:10>, <ic2:upgrade>, <advanced_solar_panels:machines:5>],
	[<advanced_solar_panels:machines:5>, <ic2:upgrade>, <auxiliumequivalence:fuel:10>, <auxiliumequivalence:fuel:10>, <compactmachines3:machine:5>, <auxiliumequivalence:fuel:10>, <auxiliumequivalence:fuel:10>, <ic2:upgrade>, <advanced_solar_panels:machines:5>],
	[<advanced_solar_panels:machines:5>, <draconicevolution:generator>, <ic2:upgrade>, <ic2:upgrade>, <enderio:block_cap_bank:3>, <ic2:upgrade>, <ic2:upgrade>, <ore:ingotUnstable>, <advanced_solar_panels:machines:5>],
	[<advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>, <advanced_solar_panels:machines:5>]
]);

#Creative Capacitor
mods.extendedcrafting.TableCrafting.addShaped(4, <draconicevolution:draconium_capacitor:2>.withTag({Energy: 1073741823}), [
	[<extendedcrafting:singularity:29>, <extendedcrafting:singularity:29>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <forge:bucketfilled>.withTag({FluidName:"ic2uu_matter",Amount:1000}), <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <extendedcrafting:singularity:29>, <extendedcrafting:singularity:29>],
	[<extendedcrafting:singularity:29>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <extendedcrafting:singularity_custom:7>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <extendedcrafting:singularity:29>],
	[<contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <solarflux:solar_panel_neutronium>, <forge:bucketfilled>.withTag({FluidName:"ic2uu_matter",Amount:1000}), <auxiliumequivalence:matter_block:3>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>],
	[<contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <solarflux:solar_panel_neutronium>, <ic2:te:86>, <ic2:te:86>, <ic2:te:86>, <auxiliumequivalence:matter_block:3>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>],
	[<forge:bucketfilled>.withTag({FluidName:"ic2uu_matter",Amount:1000}), <extendedcrafting:singularity_custom:7>, <forge:bucketfilled>.withTag({FluidName:"ic2uu_matter",Amount:1000}), <ic2:te:86>, <avaritia:resource:5>, <ic2:te:86>, <forge:bucketfilled>.withTag({FluidName:"ic2uu_matter",Amount:1000}), <extendedcrafting:singularity_custom:7>, <forge:bucketfilled>.withTag({FluidName:"ic2uu_matter",Amount:1000})],
	[<contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <auxiliumequivalence:matter_block:3>, <ic2:te:86>, <ic2:te:86>, <ic2:te:86>, <solarflux:solar_panel_chaotic>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>],
	[<contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <auxiliumequivalence:matter_block:3>, <forge:bucketfilled>.withTag({FluidName:"ic2uu_matter",Amount:1000}), <solarflux:solar_panel_chaotic>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>],
	[<extendedcrafting:singularity:29>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <extendedcrafting:singularity_custom:7>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <extendedcrafting:singularity:29>],
	[<extendedcrafting:singularity:29>, <extendedcrafting:singularity:29>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <forge:bucketfilled>.withTag({FluidName:"ic2uu_matter",Amount:1000}), <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <extendedcrafting:singularity:29>, <extendedcrafting:singularity:29>]
]);

#Creative Generator
mods.extendedcrafting.TableCrafting.addShaped(4, <draconicevolution:creative_rf_source>, [
	[<draconicevolution:draconium_capacitor:2>, <minecraft:beacon>, <appliedenergistics2:crafting_storage_64k>, <actuallyadditions:block_crystal_empowered:3>, <actuallyadditions:block_crystal_empowered:4>, <actuallyadditions:block_crystal_empowered:5>, <appliedenergistics2:crafting_storage_64k>, <minecraft:beacon>, <draconicevolution:draconium_capacitor:2>],
	[<minecraft:beacon>, <ore:blockInsaniumEssence>, <quantumflux:quibitcluster:5>, <quantumflux:quibitcluster:5>, <enderio:item_endergy_conduit:11>, <quantumflux:quibitcluster:5>, <quantumflux:quibitcluster:5>, <ore:blockInsaniumEssence>, <minecraft:beacon>],
	[<ore:blockCosmicNeutronium>, <quantumflux:quibitcluster:5>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <avaritia:resource:5>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <quantumflux:quibitcluster:5>, <ore:blockCosmicNeutronium>],
	[<ore:blockCrystalMatrix>, <quantumflux:quibitcluster:5>, <contenttweaker:chaotic_energy_core>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:13>, <extendedcrafting:singularity_ultimate>, <contenttweaker:chaotic_energy_core>, <quantumflux:quibitcluster:5>, <ore:blockCrystalMatrix>],
	[<ore:ballNeutronium>, <thermaldynamics:duct_0:5>, <avaritia:resource:5>, <extendedcrafting:material:13>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:13>, <avaritia:resource:5>, <ic2:cable:1>.withTag({type: 1 as byte, insulation: 0 as byte}), <ore:ballNeutronium>],
	[<ore:blockCrystalMatrix>, <quantumflux:quibitcluster:5>, <contenttweaker:chaotic_energy_core>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:13>, <extendedcrafting:singularity_ultimate>, <contenttweaker:chaotic_energy_core>, <quantumflux:quibitcluster:5>, <ore:blockCrystalMatrix>],
	[<ore:blockCosmicNeutronium>, <quantumflux:quibitcluster:5>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <avaritia:resource:5>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <quantumflux:quibitcluster:5>, <ore:blockCosmicNeutronium>],
	[<minecraft:beacon>, <ore:blockInsaniumEssence>, <quantumflux:quibitcluster:5>, <quantumflux:quibitcluster:5>, <extrautils2:opinium:8>, <quantumflux:quibitcluster:5>, <quantumflux:quibitcluster:5>, <ore:blockInsaniumEssence>, <minecraft:beacon>],
	[<draconicevolution:draconium_capacitor:2>, <minecraft:beacon>, <appliedenergistics2:crafting_storage_64k>, <actuallyadditions:block_crystal_empowered:2>, <actuallyadditions:block_crystal_empowered>, <actuallyadditions:block_crystal_empowered:2>, <appliedenergistics2:crafting_storage_64k>, <minecraft:beacon>, <draconicevolution:draconium_capacitor:2>]
]);

#Creative Fluid Tank
mods.extendedcrafting.TableCrafting.addShaped(4, <mekanism:machineblock2:11>.withTag({tier: 4}), [
	[<ore:ballInfinity>, <extracells:storage.fluid:6>, <extracells:storage.fluid:6>, <danknull:dank_null_panel_5>, <actuallyadditions:block_laser_relay_fluids>, <danknull:dank_null_panel_5>, <extracells:storage.fluid:6>, <extracells:storage.fluid:6>, <ore:ballInfinity>],
	[<extracells:storage.fluid:6>, <forge:bucketfilled>.withTag({FluidName:"ender_distillation",Amount:1000}), <extracells:part.base:10>, <appliedenergistics2:part:221>, <actuallyadditions:block_laser_relay_fluids>, <appliedenergistics2:part:221>, <extracells:part.base:10>, <forge:bucketfilled>.withTag({FluidName:"ender_distillation",Amount:1000}), <extracells:storage.fluid:6>],
	[<extracells:storage.fluid:6>, <extracells:part.base:10>, <forge:bucketfilled>.withTag({FluidName:"ender_distillation",Amount:1000}), <randomthings:spectreilluminator>, <mekanism:machineblock2:11>.withTag({tier:3,mekData:{fluidTank:{FluidName:"ic2uu_matter",Amount:112000}}}), <randomthings:spectreilluminator>, <forge:bucketfilled>.withTag({FluidName:"ender_distillation",Amount:1000}), <extracells:part.base:10>, <extracells:storage.fluid:6>],
	[<danknull:dank_null_panel_5>, <appliedenergistics2:part:221>, <randomthings:spectreilluminator>, <avaritia:endest_pearl>, <mekanism:machineblock2:11>.withTag({tier:3,mekData:{fluidTank:{FluidName:"supremium",Amount:112000}}}), <avaritia:endest_pearl>, <randomthings:spectreilluminator>, <appliedenergistics2:part:221>, <danknull:dank_null_panel_5>],
	[<actuallyadditions:block_laser_relay_fluids>, <actuallyadditions:block_laser_relay_fluids>, <mekanism:machineblock2:11>.withTag({tier:3,mekData:{fluidTank:{FluidName:"meat",Amount:112000}}}), <mekanism:machineblock2:11>.withTag({tier:3,mekData:{fluidTank:{FluidName:"crystal",Amount:112000}}}), <draconicevolution:creative_rf_source>, <mekanism:machineblock2:11>.withTag({tier:3,mekData:{fluidTank:{FluidName:"essence",Amount:112000}}}), <mekanism:machineblock2:11>.withTag({tier:3,mekData:{fluidTank:{FluidName:"draconium",Amount:112000}}}), <actuallyadditions:block_laser_relay_fluids>, <actuallyadditions:block_laser_relay_fluids>],
	[<danknull:dank_null_panel_5>, <appliedenergistics2:part:221>, <randomthings:spectreilluminator>, <avaritia:endest_pearl>, <mekanism:machineblock2:11>.withTag({tier:3,mekData:{fluidTank:{FluidName:"xu_demonic_metal",Amount:112000}}}), <avaritia:endest_pearl>, <randomthings:spectreilluminator>, <appliedenergistics2:part:221>, <danknull:dank_null_panel_5>],
	[<extracells:storage.fluid:6>, <extracells:part.base:10>, <forge:bucketfilled>.withTag({FluidName:"ender_distillation",Amount:1000}), <randomthings:spectreilluminator>, <mekanism:machineblock2:11>.withTag({tier:3,mekData:{fluidTank:{FluidName:"osmiridium",Amount:112000}}}), <randomthings:spectreilluminator>, <forge:bucketfilled>.withTag({FluidName:"ender_distillation",Amount:1000}), <extracells:part.base:10>, <extracells:storage.fluid:6>],
	[<extracells:storage.fluid:6>, <forge:bucketfilled>.withTag({FluidName:"ender_distillation",Amount:1000}), <extracells:part.base:10>, <appliedenergistics2:part:221>, <actuallyadditions:block_laser_relay_fluids>, <appliedenergistics2:part:221>, <extracells:part.base:10>, <forge:bucketfilled>.withTag({FluidName:"ender_distillation",Amount:1000}), <extracells:storage.fluid:6>],
	[<ore:ballInfinity>, <extracells:storage.fluid:6>, <extracells:storage.fluid:6>, <danknull:dank_null_panel_5>, <actuallyadditions:block_laser_relay_fluids>, <danknull:dank_null_panel_5>, <extracells:storage.fluid:6>, <extracells:storage.fluid:6>, <ore:ballInfinity>]
]);

#Creative Gas Tank
mods.extendedcrafting.TableCrafting.addShaped(4, <mekanism:gastank>.withTag({tier: 4}), [
	[<mekanism:gasmask>, <extracells:storage.gas:6>, <extracells:storage.gas:6>, <mekanismgenerators:hohlraum>, <enderio:item_gas_conduit:2>, <mekanismgenerators:hohlraum>, <extracells:storage.gas:6>, <extracells:storage.gas:6>, <mekanism:gasmask>], 
	[<extracells:storage.gas:6>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <advgenerators:fuel_tank>, <extendedcrafting:singularity_ultimate>, <advgenerators:fuel_tank>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <extracells:storage.gas:6>], 
	[<extracells:storage.gas:6>, <contenttweaker:chaotic_energy_core>, <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"oxygen"}}}), <extendedcrafting:frame>, <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"hydrogen"}}}), <extendedcrafting:frame>, <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"brine"}}}), <contenttweaker:chaotic_energy_core>, <extracells:storage.gas:6>], 
	[<mekanismgenerators:hohlraum>, <advgenerators:fuel_tank>, <extendedcrafting:frame>, <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"sulfurtrioxide"}}}), <mekanism:machineblock2:11>.withTag({tier:4}), <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"sulfuricacid"}}}), <extendedcrafting:frame>, <advgenerators:fuel_tank>, <mekanismgenerators:hohlraum>], 
	[<enderio:item_gas_conduit:2>, <extendedcrafting:singularity_ultimate>, <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"ethene"}}}), <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"chlorine"}}}), <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"fusionfuel"}}}), <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"water"}}}), <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"sodium"}}}), <extendedcrafting:singularity_ultimate>, <enderio:item_gas_conduit:2>], 
	[<mekanismgenerators:hohlraum>, <advgenerators:fuel_tank>, <extendedcrafting:frame>, <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"lithium"}}}), <mekanism:machineblock2:11>.withTag({tier:4}), <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"hydrogenchloride"}}}), <extendedcrafting:frame>, <advgenerators:fuel_tank>, <mekanismgenerators:hohlraum>], 
	[<extracells:storage.gas:6>, <contenttweaker:chaotic_energy_core>, <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"tritium"}}}), <extendedcrafting:frame>, <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"sulfurdioxide"}}}), <extendedcrafting:frame>, <mekanism:gastank>.withTag({tier:3,mekData:{stored:{amount:512000,gasName:"deuterium"}}}), <contenttweaker:chaotic_energy_core>, <extracells:storage.gas:6>], 
	[<extracells:storage.gas:6>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <advgenerators:fuel_tank>, <extendedcrafting:singularity_ultimate>, <advgenerators:fuel_tank>, <contenttweaker:chaotic_energy_core>, <contenttweaker:chaotic_energy_core>, <extracells:storage.gas:6>], 
	[<mekanism:gasmask>, <extracells:storage.gas:6>, <extracells:storage.gas:6>, <mekanismgenerators:hohlraum>, <enderio:item_gas_conduit:2>, <mekanismgenerators:hohlraum>, <extracells:storage.gas:6>, <extracells:storage.gas:6>, <mekanism:gasmask>]
]);

#Creative Vending Upgrade
mods.extendedcrafting.TableCrafting.addShaped(4, <storagedrawers:upgrade_creative:1>, [
	[<compacter:cobbler>, <avaritiatweaks:enhancement_crystal>, <denseneutroncollectors:triple_compressed_neutron_collector>, <minecraft:cookie>, <solarflux:solar_panel_infinity>, <minecraft:cookie>, <denseneutroncollectors:triple_compressed_neutron_collector>, <avaritiatweaks:enhancement_crystal>, <compacter:cobbler>], 
	[<avaritiatweaks:enhancement_crystal>, <projectex:matter:11>, <ore:ingotInfinity>, <contenttweaker:chaotic_energy_core>, <customcapacitors:custom_capacitor>.withTag({BlockEntityTag:{capid:"awakended_draconium"}}), <contenttweaker:chaotic_energy_core>, <ore:ingotInfinity>, <projectex:matter:11>, <avaritiatweaks:enhancement_crystal>], 
	[<denseneutroncollectors:triple_compressed_neutron_collector>, <ore:ingotInfinity>, <enderstorage:ender_storage>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_void>, <storagedrawers:upgrade_storage:4>, <enderstorage:ender_storage>, <ore:ingotInfinity>, <denseneutroncollectors:triple_compressed_neutron_collector>], 
	[<minecraft:cookie>, <contenttweaker:chaotic_energy_core>, <storagedrawers:upgrade_storage:4>, <mekanism:gastank>.withTag({tier:4}), <storagedrawers:upgrade_creative>, <mekanism:gastank>.withTag({tier:4}), <storagedrawers:upgrade_storage:4>, <contenttweaker:chaotic_energy_core>, <minecraft:cookie>], 
	[<solarflux:solar_panel_infinity>, <customcapacitors:custom_capacitor>.withTag({BlockEntityTag:{capid:"awakended_draconium"}}), <storagedrawers:upgrade_void>, <storagedrawers:upgrade_creative>, <mysticalagriculture:master_infusion_crystal>, <storagedrawers:upgrade_creative>, <storagedrawers:upgrade_void>, <customcapacitors:custom_capacitor>.withTag({BlockEntityTag:{capid:"awakended_draconium"}}), <solarflux:solar_panel_infinity>], 
	[<minecraft:cookie>, <contenttweaker:chaotic_energy_core>, <storagedrawers:upgrade_storage:4>, <mekanism:gastank>.withTag({tier:4}), <storagedrawers:upgrade_creative>, <mekanism:gastank>.withTag({tier:4}), <storagedrawers:upgrade_storage:4>, <contenttweaker:chaotic_energy_core>, <minecraft:cookie>], 
	[<denseneutroncollectors:triple_compressed_neutron_collector>, <ore:ingotInfinity>, <enderstorage:ender_storage>, <storagedrawers:upgrade_storage:4>, <storagedrawers:upgrade_void>, <storagedrawers:upgrade_storage:4>, <enderstorage:ender_storage>, <ore:ingotInfinity>, <denseneutroncollectors:triple_compressed_neutron_collector>], 
	[<avaritiatweaks:enhancement_crystal>, <projectex:matter:11>, <ore:ingotInfinity>, <contenttweaker:chaotic_energy_core>, <customcapacitors:custom_capacitor>.withTag({BlockEntityTag:{capid:"awakended_draconium"}}), <contenttweaker:chaotic_energy_core>, <ore:ingotInfinity>, <projectex:matter:11>, <avaritiatweaks:enhancement_crystal>], 
	[<compacter:cobbler>, <avaritiatweaks:enhancement_crystal>, <denseneutroncollectors:triple_compressed_neutron_collector>, <minecraft:cookie>, <solarflux:solar_panel_infinity>, <minecraft:cookie>, <denseneutroncollectors:triple_compressed_neutron_collector>, <avaritiatweaks:enhancement_crystal>, <compacter:cobbler>]
]);

#Creative Storage Cell
mods.extendedcrafting.TableCrafting.addShaped(4, <appliedenergistics2:creative_storage_cell>, [
	[<tconstruct:materials:50>, <compacter:cobbler>, <rftools:creative_screen>, <contenttweaker:chaotic_energy_core>, <tconstruct:toolforge>.withTag({textureBlock: {id: "avaritia:block_resource", Count: 1 as byte, Damage: 1 as short}}), <contenttweaker:chaotic_energy_core>, <storagedrawers:upgrade_creative>, <compacter:cobbler>, <tconstruct:materials:50>], 
	[<compacter:cobbler>, <draconicevolution:creative_rf_source>, <draconicevolution:draconium_capacitor:2>, <appliedenergistics2:creative_energy_cell>, <extrautils2:passivegenerator:6>, <bigreactors:turbinecreativesteamgenerator>, <draconicevolution:draconium_capacitor:2>, <draconicevolution:creative_rf_source>, <compacter:cobbler>], 
	[<storagedrawers:upgrade_creative>, <draconicevolution:draconium_capacitor:2>, <mekanism:gastank>.withTag({tier:4}), <ic2:te:86>, <mekanism:machineblock2:11>.withTag({tier:4}), <ic2:te:86>, <mekanism:gastank>.withTag({tier:4}), <draconicevolution:draconium_capacitor:2>, <rftools:creative_screen>], 
	[<contenttweaker:chaotic_energy_core>, <bigreactors:turbinecreativesteamgenerator>, <ic2:te:86>, <storagedrawers:upgrade_creative:1>, <storagedrawers:upgrade_creative:1>, <storagedrawers:upgrade_creative:1>, <ic2:te:86>, <appliedenergistics2:creative_energy_cell>, <contenttweaker:chaotic_energy_core>], 
	[<tconstruct:toolforge>.withTag({textureBlock: {id: "avaritia:block_resource", Count: 1 as byte, Damage: 1 as short}}), <extrautils2:passivegenerator:6>, <mekanism:machineblock2:11>.withTag({tier:4}), <storagedrawers:upgrade_creative:1>, <storagedrawers:upgrade_creative:1>, <storagedrawers:upgrade_creative:1>, <mekanism:machineblock2:11>.withTag({tier:4}), <extrautils2:passivegenerator:6>, <tconstruct:toolforge>.withTag({textureBlock: {id: "avaritia:block_resource", Count: 1 as byte, Damage: 1 as short}})], 
	[<contenttweaker:chaotic_energy_core>, <appliedenergistics2:creative_energy_cell>, <ic2:te:86>, <storagedrawers:upgrade_creative:1>, <storagedrawers:upgrade_creative:1>, <storagedrawers:upgrade_creative:1>, <ic2:te:86>, <bigreactors:turbinecreativesteamgenerator>, <contenttweaker:chaotic_energy_core>], 
	[<rftools:creative_screen>, <draconicevolution:draconium_capacitor:2>, <mekanism:gastank>.withTag({tier:4}), <ic2:te:86>, <mekanism:machineblock2:11>.withTag({tier:4}), <ic2:te:86>, <mekanism:gastank>.withTag({tier:4}), <draconicevolution:draconium_capacitor:2>, <storagedrawers:upgrade_creative>], 
	[<compacter:cobbler>, <draconicevolution:creative_rf_source>, <draconicevolution:draconium_capacitor:2>, <bigreactors:turbinecreativesteamgenerator>, <extrautils2:passivegenerator:6>, <appliedenergistics2:creative_energy_cell>, <draconicevolution:draconium_capacitor:2>, <draconicevolution:creative_rf_source>, <compacter:cobbler>], 
	[<tconstruct:materials:50>, <compacter:cobbler>, <storagedrawers:upgrade_creative>, <contenttweaker:chaotic_energy_core>, <tconstruct:toolforge>.withTag({textureBlock: {id: "avaritia:block_resource", Count: 1 as byte, Damage: 1 as short}}), <contenttweaker:chaotic_energy_core>, <rftools:creative_screen>, <compacter:cobbler>, <tconstruct:materials:50>]
]);