#Glowing Redstone
recipes.addShapeless(<contenttweaker:glowing_redstone_dust> * 2, [<minecraft:redstone>, <minecraft:glowstone_dust>]);

#Obsidian
recipes.addShapeless(<minecraft:obsidian>, [<contenttweaker:18x_obsidian>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:18x_obsidian>, [<ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>, <ore:obsidian>]);

#Clock
recipes.addShaped(<contenttweaker:9x_clock>, [[<minecraft:clock>, <minecraft:clock>, <minecraft:clock>],[<minecraft:clock>, <minecraft:clock>, <minecraft:clock>], [<minecraft:clock>, <minecraft:clock>, <minecraft:clock>]]);
recipes.addShapeless(<minecraft:clock> * 9, [<contenttweaker:9x_clock>]);

#Sugar
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:10x_sugar>, [<ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:11x_sugar>, [<ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>, <ore:listAllsugar>]);
recipes.addShapeless(<contenttweaker:11x_sugar>, [<contenttweaker:10x_sugar>,<ore:listAllsugar>]);
recipes.addShapeless(<minecraft:sugar> * 11, [<contenttweaker:11x_sugar>]);
recipes.addShapeless(<minecraft:sugar> * 10, [<contenttweaker:10x_sugar>]);

#Feather
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:32x_feather>, [<ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>, <ore:feather>]);
recipes.addShapeless(<minecraft:feather> * 32, [<contenttweaker:32x_feather>]);

#Iron Band
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:20x_iron_band>, [<projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:59x_iron_band>, [<contenttweaker:20x_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:59x_iron_band>, [<projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>, <projecte:item.pe_ring_iron_band>]);
recipes.addShapeless(<projecte:item.pe_ring_iron_band> * 20, [<contenttweaker:20x_iron_band>]);
recipes.addShapeless(<projecte:item.pe_ring_iron_band> * 59, [<contenttweaker:59x_iron_band>]);

#Neutronium Ingot
recipes.addShaped(<contenttweaker:31x_neutronium_ingot>, [[<ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:blockCosmicNeutronium>],[<ore:ingotCosmicNeutronium>, <ore:ingotCosmicNeutronium>, <ore:blockCosmicNeutronium>], [null, <ore:ingotCosmicNeutronium>, <ore:blockCosmicNeutronium>]]);
recipes.addShapeless(<avaritia:resource:4> * 32, [<contenttweaker:31x_neutronium_ingot>]);

#Crystal Matrix
recipes.addShapeless(<contenttweaker:15x_crystal_matrix>, [<ore:blockCrystalMatrix>,<contenttweaker:8x_crystal_matrix>,<ore:blockCrystalMatrix>,<ore:blockCrystalMatrix>,<ore:blockCrystalMatrix>,<ore:blockCrystalMatrix>,<ore:blockCrystalMatrix>,<ore:blockCrystalMatrix>]);
recipes.addShapeless(<contenttweaker:8x_crystal_matrix>, [<ore:blockCrystalMatrix>,<ore:blockCrystalMatrix>,<ore:blockCrystalMatrix>,<ore:blockCrystalMatrix>,<ore:blockCrystalMatrix>,<ore:blockCrystalMatrix>,<ore:blockCrystalMatrix>,<ore:blockCrystalMatrix>]);
recipes.addShapeless(<avaritia:block_resource:2> * 15, [<contenttweaker:15x_crystal_matrix>]);
recipes.addShapeless(<avaritia:block_resource:2> * 8, [<contenttweaker:8x_crystal_matrix>]);

#Draconic Energy Core
recipes.addShapeless(<contenttweaker:8x_draconic_energy_core>, [<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>]);
recipes.addShapeless(<contenttweaker:9x_draconic_energy_core>, [<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>,<draconicevolution:draconic_energy_core>]);
recipes.addShapeless(<contenttweaker:9x_draconic_energy_core>, [<contenttweaker:8x_draconic_energy_core>,<draconicevolution:draconic_energy_core>]);
recipes.addShapeless(<draconicevolution:draconic_energy_core> * 8, [<contenttweaker:8x_draconic_energy_core>]);
recipes.addShapeless(<draconicevolution:draconic_energy_core> * 9, [<contenttweaker:9x_draconic_energy_core>]);

#Infinity Catalyst
recipes.addShapeless(<avaritia:resource:5> * 3, [<contenttweaker:3x_infinity_catalyst>]);
recipes.addShapeless(<contenttweaker:3x_infinity_catalyst>, [<avaritia:resource:5>,<avaritia:resource:5>,<avaritia:resource:5>]);

#Red Matter
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:63x_red_matter>, [<projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:64x_red_matter>, [<projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:63x_red_matter>, [<contenttweaker:22x_red_matter>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:64x_red_matter>, [<contenttweaker:22x_red_matter>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>, <projecte:item.pe_matter:1>]);
recipes.addShaped(<contenttweaker:64x_red_matter>, [[null, null, null],[null, null, null], [<contenttweaker:63x_red_matter>, <projecte:item.pe_matter:1>, null]]);
recipes.addShapeless(<contenttweaker:22x_red_matter>, [<projecte:matter_block:1>,<projecte:matter_block:1>,<projecte:item.pe_matter:1>,<projecte:matter_block:1>,<projecte:item.pe_matter:1>,<projecte:matter_block:1>,<projecte:matter_block:1>]);
recipes.addShaped(<contenttweaker:22x_red_matter>, [[<projecte:matter_block:1>, <projecte:matter_block:1>, null],[<projecte:item.pe_matter:1>, <projecte:matter_block:1>, null], [<projecte:item.pe_matter:1>, <projecte:matter_block:1>, <projecte:matter_block:1>]]);
recipes.addShapeless(<projecte:item.pe_matter:1> * 64, [<contenttweaker:64x_red_matter>]);
recipes.addShapeless(<projecte:item.pe_matter:1> * 63, [<contenttweaker:63x_red_matter>]);
recipes.addShapeless(<projecte:item.pe_matter:1> * 22, [<contenttweaker:22x_red_matter>]);

#Wool
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:12x_wool>, [<ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:32x_wool>, [<ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:32x_wool>, [<contenttweaker:12x_wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>, <ore:wool>]);
recipes.addShapeless(<minecraft:wool> * 32, [<contenttweaker:32x_wool>]);
recipes.addShapeless(<minecraft:wool> * 12, [<contenttweaker:12x_wool>]);

#Chaotic Core
recipes.addShapeless(<contenttweaker:5x_chaotic_core>, [<draconicevolution:chaotic_core>,<draconicevolution:chaotic_core>,<draconicevolution:chaotic_core>,<draconicevolution:chaotic_core>,<draconicevolution:chaotic_core>]);
recipes.addShapeless(<draconicevolution:chaotic_core> * 5, [<contenttweaker:5x_chaotic_core>]);

#Neutronium Block
recipes.addShapeless(<contenttweaker:8x_neutronium_block>, [<ore:blockCosmicNeutronium>,<ore:blockCosmicNeutronium>,<ore:blockCosmicNeutronium>,<ore:blockCosmicNeutronium>,<ore:blockCosmicNeutronium>,<ore:blockCosmicNeutronium>,<ore:blockCosmicNeutronium>,<ore:blockCosmicNeutronium>]);
recipes.addShapeless(<avaritia:block_resource> * 12, [<contenttweaker:12x_neutronium_block>]);
recipes.addShapeless(<avaritia:block_resource> * 8, [<contenttweaker:8x_neutronium_block>]);
recipes.addShapeless(<contenttweaker:12x_neutronium_block>, [<contenttweaker:8x_neutronium_block>,<ore:blockCosmicNeutronium>,<ore:blockCosmicNeutronium>,<ore:blockCosmicNeutronium>,<ore:blockCosmicNeutronium>]);

#Awakened Draconium Ingot
recipes.addShapeless(<draconicevolution:draconic_ingot> * 8, [<contenttweaker:8x_awakened_draconium_ingot>]);
recipes.addShapeless(<draconicevolution:draconic_ingot> * 7, [<contenttweaker:7x_awakened_draconium_ingot>]);
recipes.addShapeless(<draconicevolution:draconic_ingot> * 4, [<contenttweaker:4x_awakened_draconium_ingot>]);
recipes.addShapeless(<contenttweaker:8x_awakened_draconium_ingot>, [<contenttweaker:7x_awakened_draconium_ingot>,<ore:ingotDraconiumAwakened>]);
recipes.addShapeless(<contenttweaker:8x_awakened_draconium_ingot>, [<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<contenttweaker:4x_awakened_draconium_ingot>,<ore:ingotDraconiumAwakened>]);
recipes.addShapeless(<contenttweaker:8x_awakened_draconium_ingot>, [<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>]);
recipes.addShapeless(<contenttweaker:7x_awakened_draconium_ingot>, [<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>]);
recipes.addShapeless(<contenttweaker:4x_awakened_draconium_ingot>, [<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>,<ore:ingotDraconiumAwakened>]);

#Glowstone
recipes.addShapeless(<minecraft:glowstone> * 64, [<contenttweaker:64x_glowstone>]);
recipes.addShapeless(<minecraft:glowstone> * 18, [<contenttweaker:18x_glowstone>]);
recipes.addShapeless(<minecraft:glowstone> * 2, [<contenttweaker:2x_glowstone>]);
recipes.addShapeless(<contenttweaker:2x_glowstone>, [<ore:glowstone>,<ore:glowstone>]);
recipes.addShapeless(<contenttweaker:2x_glowstone>, [<ore:dustGlowstone>,<ore:dustGlowstone>,<ore:dustGlowstone>,<ore:dustGlowstone>,<ore:dustGlowstone>,<ore:dustGlowstone>,<ore:dustGlowstone>,<ore:dustGlowstone>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:18x_glowstone>, [<ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:18x_glowstone>, [<ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <contenttweaker:2x_glowstone>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:64x_glowstone>, [<ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:64x_glowstone>, [<ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <contenttweaker:2x_glowstone>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:64x_glowstone>, [<ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <contenttweaker:2x_glowstone>, <contenttweaker:18x_glowstone>]);
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:64x_glowstone>, [<ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <ore:glowstone>, <contenttweaker:18x_glowstone>]);

#Awakened Core
recipes.addShapeless(<contenttweaker:9x_awakened_core>, [<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<contenttweaker:4x_awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>]);
recipes.addShapeless(<contenttweaker:9x_awakened_core>, [<contenttweaker:8x_awakened_core>,<draconicevolution:awakened_core>]);
recipes.addShapeless(<contenttweaker:8x_awakened_core>, [<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<contenttweaker:4x_awakened_core>]);
recipes.addShapeless(<contenttweaker:9x_awakened_core>, [<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>]);
recipes.addShapeless(<contenttweaker:8x_awakened_core>, [<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>]);
recipes.addShapeless(<contenttweaker:4x_awakened_core>, [<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>,<draconicevolution:awakened_core>]);
recipes.addShapeless(<draconicevolution:awakened_core> * 4, [<contenttweaker:4x_awakened_core>]);
recipes.addShapeless(<draconicevolution:awakened_core> * 8, [<contenttweaker:8x_awakened_core>]);
recipes.addShapeless(<draconicevolution:awakened_core> * 9, [<contenttweaker:9x_awakened_core>]);

#Infinity Ingot
recipes.addShapeless(<contenttweaker:11x_infinity_ingot>, [<contenttweaker:5x_infinity_ingot>,<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>]);
recipes.addShapeless(<contenttweaker:11x_infinity_ingot>, [<contenttweaker:4x_infinity_ingot>,<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>]);
recipes.addShapeless(<contenttweaker:5x_infinity_ingot>, [<contenttweaker:4x_infinity_ingot>,<ore:ingotInfinity>]);
recipes.addShapeless(<contenttweaker:5x_infinity_ingot>, [<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>]);
recipes.addShapeless(<contenttweaker:4x_infinity_ingot>, [<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>,<ore:ingotInfinity>]);
recipes.addShapeless(<avaritia:resource:6> * 11, [<contenttweaker:11x_infinity_ingot>]);
recipes.addShapeless(<avaritia:resource:6> * 5, [<contenttweaker:5x_infinity_ingot>]);
recipes.addShapeless(<avaritia:resource:6> * 4, [<contenttweaker:4x_infinity_ingot>]);

#Dark Matter
recipes.addShaped(<contenttweaker:64x_dark_matter>, [[<contenttweaker:32x_dark_matter>, <projecte:matter_block>, <projecte:matter_block>],[<projecte:matter_block>, <projecte:matter_block>, <projecte:matter_block>], [<projecte:matter_block>, <projecte:matter_block>, <projecte:matter_block>]]);
recipes.addShapeless(<contenttweaker:32x_dark_matter>, [<contenttweaker:27x_dark_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>]);
recipes.addShapeless(<contenttweaker:32x_dark_matter>, [<contenttweaker:26x_dark_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>]);
recipes.addShapeless(<contenttweaker:27x_dark_matter>, [<contenttweaker:26x_dark_matter>,<projecte:item.pe_matter>]);
recipes.addShapeless(<contenttweaker:24x_dark_matter>, [<projecte:matter_block>,<projecte:matter_block>,<projecte:matter_block>,<projecte:matter_block>,<projecte:matter_block>,<projecte:matter_block>]);
recipes.addShapeless(<projecte:item.pe_matter> * 24, [<contenttweaker:24x_dark_matter>]);
recipes.addShapeless(<projecte:item.pe_matter> * 26, [<contenttweaker:26x_dark_matter>]);
recipes.addShapeless(<projecte:item.pe_matter> * 27, [<contenttweaker:27x_dark_matter>]);
recipes.addShapeless(<projecte:item.pe_matter> * 32, [<contenttweaker:32x_dark_matter>]);
recipes.addShapeless(<projecte:item.pe_matter> * 64, [<contenttweaker:64x_dark_matter>]);
recipes.addShapeless(<contenttweaker:32x_dark_matter>, [<projecte:matter_block>,<projecte:matter_block>,<projecte:matter_block>,<projecte:matter_block>,<projecte:matter_block>,<projecte:matter_block>,<projecte:matter_block>,<projecte:matter_block>]);
recipes.addShapeless(<contenttweaker:27x_dark_matter>, [<projecte:matter_block>,<projecte:matter_block>,<projecte:item.pe_matter>,<projecte:matter_block>,<projecte:matter_block>,<projecte:item.pe_matter>,<projecte:matter_block>,<projecte:matter_block>,<projecte:item.pe_matter>]);
recipes.addShapeless(<contenttweaker:26x_dark_matter>, [<projecte:matter_block>,<projecte:matter_block>,<projecte:matter_block>,<projecte:matter_block>,<projecte:item.pe_matter>,<projecte:matter_block>,<projecte:matter_block>,<projecte:item.pe_matter>]);
recipes.addShapeless(<contenttweaker:32x_dark_matter>, [<contenttweaker:24x_dark_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>]);
recipes.addShapeless(<contenttweaker:27x_dark_matter>, [<contenttweaker:24x_dark_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>]);
recipes.addShapeless(<contenttweaker:26x_dark_matter>, [<contenttweaker:24x_dark_matter>,<projecte:item.pe_matter>,<projecte:item.pe_matter>]);

#Lapis Lazuli
mods.extendedcrafting.TableCrafting.addShapeless(0, <contenttweaker:43x_lapis_lazuli>, [<ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>, <ore:gemLapis>]);
recipes.addShapeless(<contenttweaker:63x_lapis_lazuli>, [<ore:blockLapis>,<ore:blockLapis>,<ore:blockLapis>,<ore:blockLapis>,<ore:blockLapis>,<ore:blockLapis>,<ore:blockLapis>]);
recipes.addShapeless(<minecraft:dye:4> * 63, [<contenttweaker:63x_lapis_lazuli>]);
recipes.addShapeless(<minecraft:dye:4> * 43, [<contenttweaker:43x_lapis_lazuli>]);

#Draconic Core
recipes.addShapeless(<contenttweaker:4x_draconic_core>, [<draconicevolution:draconic_core>,<draconicevolution:draconic_core>,<draconicevolution:draconic_core>,<draconicevolution:draconic_core>]);
recipes.addShapeless(<draconicevolution:draconic_core> * 4, [<contenttweaker:4x_draconic_core>]);

#Awakened Draconium Block
recipes.addShapeless(<contenttweaker:4x_awakened_draconium_block>, [<contenttweaker:2x_awakened_draconium_block>,<contenttweaker:2x_awakened_draconium_block>]);
recipes.addShapeless(<contenttweaker:4x_awakened_draconium_block>, [<draconicevolution:draconic_block>,<draconicevolution:draconic_block>,<contenttweaker:2x_awakened_draconium_block>]);
recipes.addShapeless(<contenttweaker:4x_awakened_draconium_block>, [<draconicevolution:draconic_block>,<draconicevolution:draconic_block>,<draconicevolution:draconic_block>,<draconicevolution:draconic_block>]);
recipes.addShapeless(<contenttweaker:2x_awakened_draconium_block>, [<draconicevolution:draconic_block>,<draconicevolution:draconic_block>]);
recipes.addShapeless(<draconicevolution:draconic_block> * 4, [<contenttweaker:4x_awakened_draconium_block>]);
recipes.addShapeless(<draconicevolution:draconic_block> * 2, [<contenttweaker:2x_awakened_draconium_block>]);

#Iron Ingot
recipes.addShapeless(<contenttweaker:64x_iron_ingot>, [<ore:ingotIron>,<minecraft:iron_ingot>,<ore:ingotIron>,<ore:ingotIron>,<ore:ingotIron>,<ore:blockIron>,<contenttweaker:16x_iron_ingot>,<contenttweaker:34x_iron_ingot>]);
recipes.addShapeless(<contenttweaker:64x_iron_ingot>, [<ore:blockIron>,<ore:blockIron>,<ore:blockIron>,<ore:blockIron>,<ore:ingotIron>,<ore:blockIron>,<ore:blockIron>,<ore:blockIron>]);
recipes.addShapeless(<contenttweaker:64x_iron_ingot>, [<contenttweaker:16x_iron_ingot>,<contenttweaker:16x_iron_ingot>,<contenttweaker:16x_iron_ingot>,<contenttweaker:16x_iron_ingot>]);
recipes.addShapeless(<contenttweaker:34x_iron_ingot>, [<ore:ingotIron>,<ore:ingotIron>,<contenttweaker:16x_iron_ingot>,<contenttweaker:16x_iron_ingot>]);
recipes.addShapeless(<contenttweaker:34x_iron_ingot>, [<ore:blockIron>,<contenttweaker:16x_iron_ingot>,<ore:blockIron>]);
recipes.addShapeless(<contenttweaker:16x_iron_ingot>, [<ore:ingotIron>,<ore:ingotIron>,<ore:ingotIron>,<ore:ingotIron>,<ore:blockIron>,<ore:ingotIron>,<ore:ingotIron>,<ore:ingotIron>]);
recipes.addShapeless(<minecraft:iron_ingot> * 16, [<contenttweaker:16x_iron_ingot>]);
recipes.addShapeless(<minecraft:iron_ingot> * 34, [<contenttweaker:34x_iron_ingot>]);
recipes.addShapeless(<minecraft:iron_ingot> * 64, [<contenttweaker:64x_iron_ingot>]);