mods.extendedcrafting.TableCrafting.addShaped(4, <draconicevolution:creative_rf_source>, [
    [<ic2:te:86>, <minecraft:beacon>, <appliedenergistics2:crafting_storage_64k>.noReturn(), <actuallyadditions:block_crystal_empowered:3>, <actuallyadditions:block_crystal_empowered:4>, <actuallyadditions:block_crystal_empowered:5>, <appliedenergistics2:crafting_storage_64k>.noReturn(), <minecraft:beacon>, <bigreactors:turbinecreativesteamgenerator>],
    [<minecraft:beacon>, <ore:blockInsaniumEssence>, <quantumflux:quibitcluster:5>, <quantumflux:quibitcluster:5>, <enderio:item_endergy_conduit:11>, <quantumflux:quibitcluster:5>, <quantumflux:quibitcluster:5>, <ore:blockInsaniumEssence>, <minecraft:beacon>],
    [<ore:blockCosmicNeutronium>, <quantumflux:quibitcluster:5>, <contenttweaker:chaotic_energy_core>, <draconicevolution:awakened_core>, <avaritia:resource:5>, <draconicevolution:awakened_core>, <contenttweaker:chaotic_energy_core>, <quantumflux:quibitcluster:5>, <ore:blockCosmicNeutronium>],
    [<ore:blockCrystalMatrix>, <quantumflux:quibitcluster:5>, <draconicevolution:awakened_core>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:13>, <extendedcrafting:singularity_ultimate>, <draconicevolution:awakened_core>, <quantumflux:quibitcluster:5>, <ore:blockCrystalMatrix>],
    [<ore:ballNeutronium>, <thermaldynamics:duct_0:5>, <avaritia:resource:5>, <extendedcrafting:material:13>, <ic2:debug_item>, <extendedcrafting:material:13>, <avaritia:resource:5>, <ic2:cable:1>.withTag({type: 1 as byte, insulation: 0 as byte}), <ore:ballNeutronium>],
    [<ore:blockCrystalMatrix>, <quantumflux:quibitcluster:5>, <draconicevolution:awakened_core>, <extendedcrafting:singularity_ultimate>, <extendedcrafting:material:13>, <extendedcrafting:singularity_ultimate>, <draconicevolution:awakened_core>, <quantumflux:quibitcluster:5>, <ore:blockCrystalMatrix>],
    [<ore:blockCosmicNeutronium>, <quantumflux:quibitcluster:5>, <contenttweaker:chaotic_energy_core>, <draconicevolution:awakened_core>, <avaritia:resource:5>, <draconicevolution:awakened_core>, <contenttweaker:chaotic_energy_core>, <quantumflux:quibitcluster:5>, <ore:blockCosmicNeutronium>],
    [<minecraft:beacon>, <ore:blockInsaniumEssence>, <quantumflux:quibitcluster:5>, <quantumflux:quibitcluster:5>, <extrautils2:opinium:8>, <quantumflux:quibitcluster:5>, <quantumflux:quibitcluster:5>, <ore:blockInsaniumEssence>, <minecraft:beacon>],
    [<bigreactors:turbinecreativesteamgenerator>, <minecraft:beacon>, <appliedenergistics2:crafting_storage_64k>.noReturn(), <actuallyadditions:block_crystal_empowered:2>, <actuallyadditions:block_crystal_empowered>, <actuallyadditions:block_crystal_empowered:2>, <appliedenergistics2:crafting_storage_64k>.noReturn(), <minecraft:beacon>, <ic2:te:86>]
]);

// Creative Flux Capacitor
mods.extendedcrafting.TableCrafting.addShaped(4, <draconicevolution:draconium_capacitor:2>.withTag({Energy: 1073741823}), [
    [<extendedcrafting:singularity:29>, <extendedcrafting:singularity:29>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <forge:bucketfilled>.withTag({FluidName: "ic2uu_matter", Amount: 1000}).noReturn(), <draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <extendedcrafting:singularity:29>, <extendedcrafting:singularity:29>],
    [<extendedcrafting:singularity:29>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <extendedcrafting:singularity_custom:7>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <extendedcrafting:singularity:29>],
    [<draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <contenttweaker:chaotic_energy_core>, <solarflux:solar_panel_neutronium>, <forge:bucketfilled>.withTag({FluidName: "ic2uu_matter", Amount: 1000}).noReturn(), <projectex:matter:8>, <contenttweaker:chaotic_energy_core>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>],
    [<draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <solarflux:solar_panel_neutronium>, <bigreactors:turbinecreativesteamgenerator>, <extrautils2:passivegenerator:6>, <ic2:te:86>, <projectex:matter:8>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>],
    [<forge:bucketfilled>.withTag({FluidName: "ic2uu_matter", Amount: 1000}).noReturn(), <extendedcrafting:singularity_custom:7>, <forge:bucketfilled>.withTag({FluidName: "ic2uu_matter", Amount: 1000}).noReturn(), <appliedenergistics2:creative_energy_cell>, <avaritia:resource:5>, <appliedenergistics2:creative_energy_cell>, <forge:bucketfilled>.withTag({FluidName: "ic2uu_matter", Amount: 1000}).noReturn(), <extendedcrafting:singularity_custom:7>, <forge:bucketfilled>.withTag({FluidName: "ic2uu_matter", Amount: 1000}).noReturn()],
    [<draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <projectex:matter:8>, <ic2:te:86>, <extrautils2:passivegenerator:6>, <bigreactors:turbinecreativesteamgenerator>, <solarflux:solar_panel_chaotic>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>],
    [<draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <contenttweaker:chaotic_energy_core>, <projectex:matter:8>, <forge:bucketfilled>.withTag({FluidName: "ic2uu_matter", Amount: 1000}).noReturn(), <solarflux:solar_panel_chaotic>, <contenttweaker:chaotic_energy_core>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>],
    [<extendedcrafting:singularity:29>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <extendedcrafting:singularity_custom:7>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <extendedcrafting:singularity:29>],
    [<extendedcrafting:singularity:29>, <extendedcrafting:singularity:29>, <draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <forge:bucketfilled>.withTag({FluidName: "ic2uu_matter", Amount: 1000}).noReturn(), <draconicevolution:awakened_core>, <draconicevolution:awakened_core>, <extendedcrafting:singularity:29>, <extendedcrafting:singularity:29>]
]);
